name: Auto-update charm libraries

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  auto-update-libs:
    uses: canonical/operator-workflows/.github/workflows/auto_update_charm_libs.yaml@main
    secrets: inherit
